config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  get '/menu'  => 'home#menu', as: 'menu'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

  resources :products
  resources :categories


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products
  
end

app/models/product.rb
class Product < ApplicationRecord

belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to categories_path
      else
        render :new
      end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
      if @category.update(category_params)
         redirect_to categories_path
      else
          render :edit
      end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :value)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def menu
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

      if @product.save
        redirect_to products_path, notice: 'Product was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
      if @product.update(product_params)
        redirect_to product_path(@product), notice: 'Product was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_id, :name, :description, :price, :stock, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4">
    </div>
    <div class="col-lg-4">
      <%= simple_form_for @category, :html => { :class => "form-vertical" } do |f| %>

      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :value %>

      <%= f.button :submit, :class => '' %>
      <%= link_to t('Cancelar', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default' %>

      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
	<h1>Categorias</h1>
<div class="page-header">
	<%= link_to "Cadastrar", new_category_path, class: 'btn btn-primary pull-right' %>

</div>
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>Nome</th>
			<th>Descrição</th>
      <th>Valor</th>
      <th>Quantidade</th>
      <th>Inserção</th>
      <th>Opções</th>
    </tr>
  </thead>


  <tbody>
    <% @categories.each do |category| %>
      <tr>
  			<td style="font-size:17px;"> <b><%= category.name %></b></td>
  			<td style="font-size:17px;"> <b><%= category.description %></b></td>
  			<td style="font-size:17px;"> <b><%= category.value %></b></td>
        <td style="font-size:17px;"> <b><%= category.products.size %></b></td>
        <td style="font-size:17px;"> <b><%= category.created_at %></b></td>
        <td>
          <%= link_to "Ver", category, class: 'btn btn-info' %>
          <%= link_to "Editar", edit_category_path(category), class: 'btn btn-primary' %>
          <%= link_to "Apagar", category,
  					data: { method: :delete},	class: 'btn btn-danger'
  				%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

      <dl class="dl-horizontal">
        <ul>
        	<li>ID: <%= @category.id -%></li>
        	<li>Nome: <%= @category.name -%></li>
        	<li>Description: <%= @category.description -%></li>
          <li>Valor: <%= number_to_currency @category.value %></li>
        	<li>Created At: <%= @category.created_at -%></li>
        </ul>
      </dl>

      <%= link_to t('.back', :default => t("helpers.links.back")),
                    category_path, :class => 'btn btn-default'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_category_path(@category), :class => 'btn btn-default' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    category_path(@category),
                    :method => 'delete', :class => 'btn btn-danger' %>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="page-content">

  <section class="full-section dark-section" id="section-17" data-stellar-background-ratio="0.1">
    <div class="full-section-container">

      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="headline style-1 text-center">

              <p>Crypto Trade Systems</p>
              <h3>Developed by us, to solve your problems.</h3>

            </div><!-- headline -->

            <br>

            <p class="text-center"><%= link_to "Admin", "/menu", class: 'btn btn-default btn-lg' %></p>


          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->

      <br>
      <br>
      <br>

      <div class="container">
        <div class="row">
          <div class="col-sm-3">

            <div class="service-box style-1">

              <h4>01</h4>

              <div class="service-box-content">

                <h4><a href="single-service.html">Estoque</a></h4>

                <p style="font-size:16px;">Tenha seu estoque a um clique. Insira, remova, atualize; é simples é prático.</p>

              </div><!-- service-box-content -->

            </div><!-- service-box -->

          </div><!-- col -->
          <div class="col-sm-3">

            <div class="service-box style-1">

              <h4>02</h4>

              <div class="service-box-content">

                <h4><a href="single-service.html">Clasificação</a></h4>

                <p style="font-size:16px;">Estoque totalmente organizado e dividido, sem disperdicio de tempo.</p>

              </div><!-- service-box-content -->

            </div><!-- service-box -->

          </div><!-- col -->
          <div class="col-sm-3">

            <div class="service-box style-1">

              <h4>03</h4>

              <div class="service-box-content">

                <h4><a href="single-service.html">Cadastro</a></h4>

                <p style="font-size:16px;">Cadastre clientes e fornecedores, mais rápido e prático do que se imagina.</p>

              </div><!-- service-box-content -->

            </div><!-- service-box -->

          </div><!-- col -->
          <div class="col-sm-3">

            <div class="service-box style-1">

              <h4>04</h4>

              <div class="service-box-content">

                <h4><a href="single-service.html">Controle</a></h4>

                <p style="font-size:16px;">Gerencie tudo com um sistema de relatorios totalmente personalizado.</p>

              </div><!-- service-box-content -->

            </div><!-- service-box -->

          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->

    </div><!-- full-section-container -->
  </section><!-- full-section -->

  <section class="full-section dark-section" id="section-18" data-stellar-background-ratio="0.1">
    <div class="full-section-container">

      <div class="container">
        <div class="row">
          <div class="col-sm-12">

            <div class="image-box">

              <div class="image-box-thumbnail" style="background-image:url(<%= asset_path "image-13.jpg"%>); min-height:600px;"></div>
              <div class="image-box-details">

                <div class="headline style-1 text-right">

                  <p>Deixe nos apresentarmos</p>
                  <h3>Contate-nos com suas duvidas ou sujestões</h3>

                </div><!-- headline -->

                <p class="text-right">Donec aliquam lorem quis nibh viverra vehicula. Donec pharetra
                lacus in dolor ultricies mollis eget sit amet ipsum. Suspendisse eu imperdiet tellus,
                non tempus tortor. Duis ultricies eu nunc non placerat. Praesent congue quam ipsum,
                at consequat felis eleifend id. Aliquam pellentesque sapien at mollis sodales. Donec
                aliquam lorem quis nibh viverra vehicula. Donec pharetra lacus in dolor ultricies
                mollis eget sit amet ipsum. Suspendisse eu imperdiet tellus, non tempus tortor. Duis
                ultricies eu nunc non placerat. Praesent congue quam ipsum, at consequat felis eleifend
                id. Aliquam pellentesque sapien at mollis.</p>

              </div><!-- image-box-details -->

            </div><!-- image-box -->

          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->

    </div><!-- full-section-container -->
  </section><!-- full-section -->

  <section class="full-section dark-section parallax" id="section-19" data-stellar-background-ratio="0.1">
    <div class="full-section-container">

      <div class="container">
        <div class="row">
          <div class="col-sm-12">

            <div class="headline style-2">

              <p>O que é falado sobre nos</p>
              <h2>Testemunho de clientes</h2>

            </div><!-- headline -->

          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">

        <div class="item active">
          <div class="container">
            <div class="row carousel-caption">
              <div class="col-sm-offset-3 col-sm-9">

                <div class="testimonial">

                  <blockquote>
                    <p>A começar pela equipe de atendimento tecnico é tudo uma maravilha. Atenciosos como sempre eles se preocupam com nossas nescessidades. O sistema é fluido e chaga  a ser um pouco mais do que eu esperava, surpreendendo nossa equipe positivamente de forma constante.</p>
                  </blockquote>

              <%= image_tag "image-1.jpg", class: 'center-imgs' %>

              <h6 style="font-size:18px;">
                Renato Torres<br>
                <span>CTO da Dotcell.</span>
              </h6>

              </div><!-- testimonial -->

            </div><!-- col -->
          </div><!-- row -->
        </div><!-- container -->
      </div><!-- item -->

      <div class="item">
        <div class="container">
          <div class="row carousel-caption">
            <div class="col-sm-offset-3 col-sm-9">

              <div class="testimonial">

                <blockquote>
                  <p>Posso dizer sem sombra de duvidas que o sistema de relatorios é o que nos mais precisavamos aqui na nossa empresa, um sistema robusto que nos trás mestricas de tudo que precisamos .</p>
                </blockquote>

                  <%= image_tag "bg-3.png", size: '80x80' , class: 'center-imgs' %>

                    <h6 style="font-size:18px;">
                      Rubens Soares<br>
                    <span>Gerente da Teresina Celular.</span>
                    </h6>

            </div><!-- testimonial -->

          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->
    </div><!-- item -->

    <div class="item">
      <div class="container">
        <div class="row carousel-caption">
          <div class="col-sm-offset-3 col-sm-9">

            <div class="testimonial">

              <blockquote>
                <p>Posso dizer sem sombra de duvidas que o sistema de relatorios é o que nos mais precisavamos aqui na nossa empresa, um sistema robusto que nos trás mestricas de tudo que precisamos .</p>
              </blockquote>

                <%= image_tag "image-2.jpg", size: '80x80' , class: 'center-imgs' %>

                  <h6 style="font-size:18px;">
                    Gilberto Gomes<br>
                  <span>China Cell.</span>
                  </h6>

          </div><!-- testimonial -->

        </div><!-- col -->
      </div><!-- row -->
    </div><!-- container -->
  </div><!-- item -->

    </div>
  </div>

    </div><!-- full-section-container -->
  </section><!-- full-section -->

</div>
<div id="footer-bottom">

				<div class="container">
					<div class="row">
						<div class="col-sm-3 col-md-4">

							<div class="widget widget-text">

								<div>

									<img src="<%= asset_path "logo-3.png"%>" alt="">

								</div>

							</div><!-- widget-text -->

						</div><!-- col -->
						<div class="col-sm-5 col-md-4">

							<div class="widget widget-text">

								<div>

									<p class="copyright text-center">2016 Crypto Trade Systems &copy; All Rights Reserved</p>

								</div>

							</div><!-- widget-text -->

						</div><!-- col -->
						<div class="col-sm-4">

							<div class="widget widget-social">

								<div class="social-media">

									<a class="pinterest" href="#"><i class="fa fa-pinterest"></i></a>
									<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
									<a class="instagram" href="#"><i class="fa fa-instagram"></i></a>
									<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
									<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>

								</div><!-- social-media -->

							</div><!-- widget-social -->

						</div><!-- col -->
					</div><!-- row -->
				</div><!-- container -->

			</div><!-- FOOTER BOTTOM -->

app/views/home/menu.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Painel Administrativo</h1>
      <br>

    </div>
    <div class="col-md-6">
      <h3 style="display: flex;justify-content: center;">Produtos</h3>
    </div>
    <div class="col-md-6">
      <h3 style="display: flex;justify-content: center;">Categorias</h3>
    </div>
      <div class="col-md-6 flex">
        <%= link_to image_tag(asset_path "categ.jpg"), '/products', class: 'thumbnail', title: "Produto"%>
      </div>
      <div class="col-md-6 flex">
        <%= link_to image_tag(asset_path "stock.jpg"), '/categories', class: 'thumbnail', title: "Categoria" %>
      </div>
  </div>
</div>

app/views/layouts/_navsite.html.erb
<%= nav_bar :static => :top,  :brand => 'Home',responsive: true, fluid: true do %>

  <%= menu_group do %>
    <%= menu_item "Admin", '/menu' %>
  <% end %>

  <%= menu_group pull: :right do %>
    <% if user_signed_in? -%>
      <%= menu_item "Produtos", products_path %>
      <%= menu_item "Categoria", categories_path %>

      <%= drop_down current_user.email do %>
        <%= menu_item 'Editar Perfil', edit_user_registration_path -%>
      <% end -%>

      <%= menu_item 'Sair', destroy_user_session_path, method: :delete -%>
    <% else -%>
      <%= menu_item 'Login', new_user_session_path -%>
      <%= menu_item 'Cadastre-se', new_user_registration_path -%>
    <% end -%>
  <% end -%>

<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navsite' %>
    </header>
      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <div class="container-fluid">
        <%= yield %>
      </div>

  </body>
</html>

app/views/products/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4">
    </div>
    <div class="col-lg-4">
      <%= simple_form_for @product, :html => { :class => "form-vertical" } do |f| %>

      <%= f.association :category, prompt: 'Selecione a Categoria' %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :stock %>
      <%= f.input :status %>

      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn btn-default' %>

      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
	<h1>Estoque</h1>
<div class="page-header">
	<%= link_to "Cadastrar", new_product_path, class: 'btn btn-primary pull-right' %>

</div>
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Nome</th>
			<th>Descrição</th>
			<th>Status</th>
      <th>Quantidade</th>
      <th>Valor</th>
      <th>Inserção</th>
      <th>Opções</th>
    </tr>
  </thead>


  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td style="font-size:17px;"> <b><%= product.category.try(:name) %></b></td>
  			<td style="font-size:17px;"> <b><%= product.name %></b></td>
  			<td style="font-size:17px;"> <b><%= product.description %></b></td>
  			<td style="font-size:17px;"> <b><%= product.status %></b></td>
        <td style="font-size:17px;"> <b><%= product.stock %></b></td>
        <td style="font-size:17px;"> <b><%= number_to_currency product.price %></b></td>
        <td style="font-size:17px;"> <b><%= product.created_at %></b></td>
        <td>
          <%= link_to "Ver", product, class: 'btn btn-info' %>
          <%= link_to "Editar", edit_product_path(product), class: 'btn btn-primary' %>
          <%= link_to "Apagar", product,
  					data: { method: :delete},	class: 'btn btn-danger'
  				%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

      <dl class="dl-horizontal">
        <ul>
        	<li>ID: <%= @product.category_id -%></li>
        	<li>Nome: <%= @product.name -%></li>
        	<li>Description: <%= @product.description -%></li>
        	<li>Status: <%= @product.status -%></li>
        	<li>Quantidade: <%= @product.stock -%></li>
          <li>Valor: <%= number_to_currency @product.price %></li>
        	<li>Created At: <%= @product.created_at -%></li>
        </ul>
      </dl>

      <%= link_to t('.back', :default => t("helpers.links.back")),
                    products_path, :class => 'btn btn-default'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_product_path(@product), :class => 'btn btn-default' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    product_path(@product),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>

    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>